
skillMetadata:
  sections:
    - name: Options << Name of section
      fields:
        - name: myura_url
          type: text
          label: URL for Myura device
          value: ""
          placeholder: enter url